apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vm-proxy-auth.fullname" . }}-config
  labels:
    {{- include "vm-proxy-auth.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (toYaml .Values.config) . | nindent 4 }}
